Repository express-validator/express-validator, pull requests merged in 2021-09, with the labels that each got.

#1022 feat(oneOf): add new error types
  docs/api-check.md
  jest.config.js
  src/middlewares/__snapshots__/one-of.spec.ts.snap
  src/middlewares/one-of.spec.ts
  src/middlewares/one-of.ts
Labels: PR: new feature, PR: v7.0.0

#1069 feat: bump validator to 13.6.0
  declarations/validator.d.ts
  package-lock.json
  package.json
  src/chain/validators-impl.ts
  src/chain/validators.ts
  src/options.ts
Labels: PR: dependencies, PR: new feature

#1074 feat(`checkSchema`): add `.if` support
  src/middlewares/schema.spec.ts
  src/middlewares/schema.ts
Labels: PR: enhancement, area: schema

#1072 fix: add type for `checkSchema` function return
  src/middlewares/schema.ts
Labels: typescript, PR: bug fix

#1092 fix(`checkSchema`): correctly allow falsy values as options
  src/middlewares/schema.spec.ts
  src/middlewares/schema.ts
  src/validation-result.ts
Labels: PR: bug fix, area: schema
