Repository express-validator/express-validator, pull requests merged in 2021-03, with the labels that each got.

#993 breaking: remove deprecated APIs
  .gitignore
  .prettierignore
  check/index.ts
  docs/api-filter.md
  filter/index.ts
  package.json
  src/chain/index.ts
  src/chain/sanitization-chain.ts
  src/index.ts
  src/middlewares/sanitization-chain-builders.spec.ts
  src/middlewares/sanitization-chain-builders.ts
  src/middlewares/sanitize.spec.ts
  src/middlewares/sanitize.ts
  src/middlewares/schema.ts
  website/i18n/en.json
  website/sidebars.json
Labels: PR: v7.0.0

#1004 fix(security): Bump lodash version to 4.17.21
  package-lock.json
  package.json
Labels: PR: dependencies

#857 feat(website): add DocSearch as recommended by docusaurus
  website/siteConfig.js
Labels: docs

#983 deps: bump typescript to 4.1.3 and linting deps
  package-lock.json
  package.json
  src/chain/context-runner-impl.spec.ts
  tsconfig.json
Labels: PR: dependencies
